---
execute:
  daemon: false
  freeze: auto
---

# Small table {.unnumbered}

```{=html}
<table>
    <tr>
        <th>Colonna 1</th>
        <th>Colonna 2</th>
        <th>Colonna 3</th>
    </tr>
    <tr>
        <td>Riga 1, Cellula 1 <span data-qmd="^[footsample]"></span></td>
        <td>Riga 1, Cellula 2</td>
        <td>Riga 1, Cellula 3</td>
    </tr>
    <tr>
        <td>Riga 2, <span data-qmd="[-@sec-soggetti-destinatari]"></span></td>
        <td>Riga 2, <span data-qmd="[@sec-soggetti-destinatari]"></span></td>
        <td>Riga 2, Cellula 3</td>
    </tr>
</table>
```

### Row span test

+-------------+---------+
| field a     | field b |
+=============+=========+
| lorem ipsum | one     |
|             +---------+
|             | two     |
|             +---------+
|             | three   |
+-------------+---------+
| amet        | one     |
+-------------+---------+
| well done   | one     |
|             +---------+
|             | two     |
+-------------+---------+


+---------------------+----------+
| Property            | Earth    |
+=============+=======+==========+
|             | min   | -89.2 °C |
| Temperature +-------+----------+
| 1961-1990   | mean  | 14 °C    |
|             +-------+----------+
|             | max   | 56.7 °C  |
+-------------+-------+----------+


### R test

```{r}
#| warning: false
#| message: false
#| echo: false
#| output: false

library(ftExtra)
library(flextable)
library(openxlsx)
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| output: asis

atab <- read.xlsx("debug/row-span.xlsx", sheet=1, colNames = TRUE, fillMergedCells = TRUE)

ft1 <- flextable(atab) |>
  width(width = c(2.5, 1, 1.2)) |>
  merge_v(j = "Property") |>
  theme_vanilla() |>
  mk_par(j = 2, part = "header", value = as_paragraph(" ")) |>
  align(j = 3, align = "right", part = "all")

flextable_to_rmd(colformat_md(ft1, part="body"))
```
