project:
  type: book
  resources:
    - "lg.csl"
    - "rawdata/LG-Open-Data_v.1.0.docx"
  render:
    - "ndr.qmd"
    - "!note.md"
    - "!debug/*"
language:
  section-title-appendices: "Allegati"

book:
  title: "Linee guida Open Data"
  description: "La versione HTML a cura dell'associazione onData"
  sharing: [twitter, facebook,linkedin]
  twitter-card:
    creator: "@ondatait"
    image: "/immagini/linee_guida_open_data.png"
  site-url: https://ondata.github.io/linee-guida-opendata
  open-graph:
    locale: "it_IT"
    image: "/immagini/linee_guida_open_data.png"
  sidebar:
    logo: immagini/logo.png
    search: true
    collapse-level: 1
    border: true
    style: floating
  chapters:
    - text: "Home"
      file: index.qmd
    - text: "Note di redazione"
      file: ndr.qmd
    - text: "---"
    - part: "Linee guida"
      chapters:
        - gruppo-di-lavoro.qmd
        - prefazione.qmd
        - introduzione.qmd
        - capitolo-1.qmd
        - capitolo-2.qmd
        - capitolo-3.qmd
        - capitolo-4.qmd
        - capitolo-5.qmd
        - capitolo-6.qmd
        - capitolo-7.qmd
    # - part: "Test"
    #   chapters:
    #     - debug/raw-html-cr.qmd
    #     - test_cit.qmd
    #     - small_table.qmd
    #     - debug/column-page-inset.qmd
    #     - debug/cr-label.qmd
    #     - debug/home.qmd
  appendices:
    - allegato-A.qmd
    - allegato-B.qmd
    - allegato-C.qmd
    - allegato-D.qmd

  repo-url: https://github.com/ondata/linee-guida-opendata
  repo-branch: main
  repo-actions: [edit, issue]

  page-footer:
    border: true
    background: light
    left: |
      A cura dell'[associazione onData](https://ondata.it).
    right: |
      Costruito con <a href="https://quarto.org/">Quarto</a>.
    center: |
      [Licenza CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)

format:
  html:
    lang: "it-IT"
    toc-depth: 4
    theme:
      - cosmo
      - styles.scss
    footnotes-hover: false
    citations-hover: false
    include-in-header: include/script.html
    crossrefs-hover: false
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: '^.*\.github\.io\/'

website:
  back-to-top-navigation: true
  announcement:
    icon: envelope-arrow-down
    dismissable: false
    content: "[Iscriviti alla **newsletter di onData**](https://ondata.substack.com/)"
    type: primary
    position: above-navbar

crossref:
  custom:
    - kind: float
      reference-prefix: Requisito
      key: req
    - kind: float
      reference-prefix: Raccomandazione
      key: racc
    - kind: float
      reference-prefix: Risorsa
      key: res
  appendix-title: "Allegato"

execute:
  daemon: false
  freeze: auto

# filters:
#   - fix_refs.lua
