project:
  type: book

book:
  title: "Linee guida Open Data"
  chapters:
    - index.qmd
    - gruppo-di-lavoro.qmd
    - prefazione.qmd
    - introduzione.qmd
    - capitolo-1.qmd
    - capitolo-2.qmd
    - capitolo-3.qmd
    - capitolo-4.qmd
    - references.qmd

  repo-url: https://github.com/aborruso/linee-guida-opendata
  repo-branch: main
  repo-actions: [edit, issue]

  page-footer:
    left: |
      A cura dell'[associazione onData](https://ondata.it).
    right: |
      Costruito con <a href="https://quarto.org/">Quarto</a>.
    center: |
      [Licenza CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)

format:
  html:
    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss
    footnotes-hover: false

website:
  back-to-top-navigation: true

bibliography: references.bib

execute:
  daemon: false
  freeze: auto
