project:
  type: book
  resources:
    - "lg.csl"
language:
  section-title-appendices: "Allegati"

book:
  title: "Linee guida Open Data"
  sharing: [twitter, facebook]
  sidebar:
    logo: immagini/logo.png
    search: true
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Linee guida"
      chapters:
        - gruppo-di-lavoro.qmd
        - prefazione.qmd
        - introduzione.qmd
        - capitolo-1.qmd
        - capitolo-2.qmd
        - capitolo-3.qmd
        - capitolo-4.qmd
        - capitolo-5.qmd
        - capitolo-6.qmd
        - capitolo-7.qmd
    - part: "Test"
      chapters:
        - test_cit.qmd
        - references.qmd
        - small_table.qmd
        - debug/column-page-inset.qmd
        - debug/cr-label.qmd
  appendices:
    - allegato-A.qmd
    - allegato-B.qmd
    - allegato-C.qmd
    - allegato-D.qmd

  repo-url: https://github.com/aborruso/linee-guida-opendata
  repo-branch: main
  repo-actions: [edit, issue]

  page-footer:
    left: |
      A cura dell'[associazione onData](https://ondata.it).
    right: |
      Costruito con <a href="https://quarto.org/">Quarto</a>.
    center: |
      [Licenza CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)

format:
  html:
    lang: "it-IT"
    theme:
      - cosmo
      - styles.scss
    footnotes-hover: false
    citations-hover: false
    include-in-header: include/script.html
    crossrefs-hover: false
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*\.github\.io\/'

website:
  back-to-top-navigation: true

bibliography: references.bib
nocite: '@*'
csl: lg.csl

crossref:
  custom:
    - kind: float
      reference-prefix: Requisito
      key: req
    - kind: float
      reference-prefix: Raccomandazione
      key: racc

execute:
  daemon: false
  freeze: auto
