# Normativa di riferimento

Sono riportati di seguito gli atti normativi di riferimento del presente documento.

## Legislazione nazionale ed europea {#sec-legislazione-nazionale-ed-europea}

::: {.no-head}

| label | testo |
| --- | --- |
| [**CAD**]{#CAD} | [Decreto legislativo 7 marzo 2005, n. 82 recante "Codice dell'amministrazione digitale"](https://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=2005-05-16&atto.codiceRedazionale=005G0104&atto.articolo.numero=0&atto.articolo.sottoArticolo=1&atto.articolo.sottoArticolo1=10&qId=b8226c0a-4e5d-4b0f-814e-ed010e5ef111&tabID=0.755394932407083&title=lbl.dettaglioAtto) |
| [**D-LGS-196-2003**]{#D-LGS-196-2003} | [Decreto legislativo 30 giugno 2003, n. 196 e s.m.i. recante "Codice in materia di protezione dei dati personali, recante disposizioni per l'adeguamento dell'ordinamento nazionale al regolamento (UE) n. 2016/679 del Parlamento europeo e del Consiglio, del 27 aprile 2016, relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali, nonché alla libera circolazione di tali dati e che abroga la direttiva 95/46/CE"](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2003-06-30;196) |
| [**D-LGS-36-2006**]{#D-LGS-36-2006} | [Decreto legislativo 24 gennaio 2006, n. 36 recante "Attuazione della direttiva (UE) 2019/1024 relativa all'apertura dei dati e al riutilizzo dell'informazione del settore pubblico che ha abrogato la direttiva 2003/98/CE"](https://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=2006-02-14&atto.codiceRedazionale=006G0046&atto.articolo.numero=0&atto.articolo.sottoArticolo=1&atto.articolo.sottoArticolo1=10&qId&tabID=0.755394932407083&title=lbl.dettaglioAtto) |
| [**D-LGS-32-2010**]{#D-LGS-32-2010} | [Decreto legislativo 27 gennaio 2010, n. 32 recante "Attuazione della direttiva 2007/2/CE, che istituisce un'infrastruttura per l'informazione territoriale nella Comunità europea (INSPIRE)"](https://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=2010-03-09&atto.codiceRedazionale=010G0043&atto.articolo.numero=0&atto.articolo.sottoArticolo=1&atto.articolo.sottoArticolo1=10&qId=2fd183d5-5d95-4ee3-825d-fd11541e0173&tabID=0.755394932407083&title=lbl.dettaglioAtto) |
| [**D-LGS-33-2013**]{#D-LGS-33-2013} | [Decreto legislativo 14 marzo 2013, n. 33 recante "Riordino della disciplina riguardante il diritto di accesso civico e gli obblighi di pubblicità, trasparenza e diffusione di informazioni da parte delle pubbliche amministrazioni"](https://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=2013-04-05&atto.codiceRedazionale=13G00076&atto.articolo.numero=0&atto.articolo.sottoArticolo=1&atto.articolo.sottoArticolo1=10&qId=7975f643-59d6-4336-a510-5cd8203118ff&tabID=0.755394932407083&title=lbl.dettaglioAtto) |
| [**D-LGS-51-2018**]{#D-LGS-51-2018} | [Decreto legislativo 18 maggio 2018, n. 51 recante "Attuazione della direttiva (UE) 2016/680 del Parlamento europeo e del Consiglio, del 27 aprile 2016, relativa alla protezione delle persone fisiche con riguardo al trattamento dei dati personali da parte delle autorità competenti a fini di prevenzione, indagine, accertamento e perseguimento di reati o esecuzione di sanzioni penali, nonché alla libera circolazione di tali dati e che abroga la decisione quadro 2008/977/GAI del Consiglio"](https://www.normattiva.it/uri-res/N2Ls?urn%3Anir%3Astato%3Adecreto.legislativo%3A2018-05-18%3B51!vig) |
| [**D-LGS-200-2021**]{#D-LGS-200-2021} | [Decreto legislativo 8 novembre 2021, n. 200 recante "Attuazione della direttiva (UE) 2019/1024 del Parlamento europeo e del Consiglio, del 20 giugno 2019, relativa all'apertura dei dati e al riutilizzo dell'informazione del settore pubblico (rifusione)"](https://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=2021-11-30&atto.codiceRedazionale=21G00213&atto.articolo.numero=0&atto.articolo.sottoArticolo=1&atto.articolo.sottoArticolo1=10&qId=bb256807-08f4-40e8-aa14-579a21f84ec1&tabID=0.755394932407083&title=lbl.dettaglioAtto) |
| [**INSPIRE-DIR**]{#INSPIRE-DIR} | [Direttiva 2007/2/CE del Parlamento europeo e del Consiglio, del 14 marzo 2007, che istituisce un'Infrastruttura per l'informazione territoriale nella Comunità europea (INSPIRE)](https://eur-lex.europa.eu/legal-content/IT/TXT/?uri=CELEX:32007L0002) |
| [**DIR-2016-680**]{#DIR-2016-680} | [Direttiva (UE) 2016/680 del Parlamento europeo e del Consiglio del 27 aprile 2016 relativa alla protezione delle persone fisiche con riguardo al trattamento dei dati personali da parte delle autorità competenti a fini di prevenzione, indagine, accertamento e perseguimento di reati o esecuzione di sanzioni penali, nonché alla libera circolazione di tali dati e che abroga la decisione quadro 2008/977/GAI del Consiglio](https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A32016L0680&from=IT) |
| [**OD-DIR**]{#OD-DIR} | [Direttiva (UE) 2019/1024 del Parlamento Europeo e del Consiglio del 20 giugno 2019 relativa all'apertura dei dati e al riutilizzo dell'informazione del settore pubblico (rifusione)](https://eur-lex.europa.eu/legal-content/IT/TXT/?uri=CELEX%3A32019L1024&qid=1658755144769) |
| [**GDPR**]{#GDPR} | [Regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio del 27 aprile 2016 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali, nonché alla libera circolazione di tali dati e che abroga la direttiva 95/46/CE (regolamento generale sulla protezione dei dati)](https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A32016R0679) |
| [**REG-868-22**]{#REG-868-22} | [Regolamento (UE) 2022/868 del Parlamento europeo e del Consiglio del 30 maggio 2022 relativo alla governance europea dei dati e che modifica il regolamento (UE) 2018/1724 (Regolamento sulla governance dei dati)](https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A32022R0868&from=IT) |
| [**REG-HVD**]{#REG-HVD} | [Regolamento di esecuzione (UE) 2023/138 della Commissione del 21 dicembre 2022 che stabilisce un elenco di specifiche serie di dati di elevato valore e le relative modalità di pubblicazione e riutilizzo](https://eur-lex.europa.eu/legal-content/IT/TXT/?qid=1676740512286&uri=CELEX%3A32023R0138) |

: {tbl-colwidths="[20,80]" .table-sm .table-striped}

:::

## Linee Guida {#sec-linee-guida}

::: {.no-head}
| label | testo |
| --- | --- |
| [**LG-CONS**]{#LG-CONS} | [Linee Guida sulla formazione, gestione e conservazione dei documenti informatici](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_sul_documento_informatico.pdf), adottate con la Determinazione AgID n. 407/2020 come modificata con la Determinazione AgID n. 371/2021 |
| [**LG-INT**]{#LG-INT} | [Linee Guida sull'interoperabilità tecnica delle Pubbliche Amministrazioni](https://trasparenza.agid.gov.it/archivio28_provvedimenti-amministrati%20vi_0_123008_725_1.html), adottate con la Determinazione AgID n. 547/2021 del 1° ottobre 2021 |
| [**LG-PDND**]{#LG-PDND} | [Linee Guida sull'infrastruttura tecnologica della Piattaforma Digitale Nazionale Dati per l'interoperabilità dei sistemi informativi e delle basi di dati](https://trasparenza.agid.gov.it/archivio28_provvedimenti-ammini strativi_0_123064_725_1.html), adottate con la Determinazione AgID n. 627/2021 del 15 dicembre 2021 |
| [**LG-RNDT**]{#LG-RNDT} | [Linee Guida recanti regole tecniche per la definizione e l'aggiornamento del contenuto del Repertorio Nazionale dei Dati Territoriali](https://trasparenza.agid.gov.it/archivio28_provvedimenti-amministrati%20vi_0_123123_725_1.html), adottate con la Determinazione AgID n. 50/2022 del 28 febbraio 2022 |
| [**LG-SIC**]{#LG-SIC} | [Linee Guida Tecnologie e standard per la sicurezza dell'interoperabilità tramite API dei sistemi informatici](https://trasparenza.agid.gov.it/archivio28_provvedimenti-amministrati vi_0_123008_725_1.html), adottate con la Determinazione AgID n. 547/2021 del 1° ottobre 2021 |
| [**LG-GPDP**]{#LG-GPDP} | [Linee guida in materia di trattamento di dati personali, contenuti anche in atti e documenti amministrativi, effettuato per finalità di pubblicità e trasparenza sul web da soggetti pubblici e da altri enti obbligati](https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/3134436), adottate con provvedimento del Garante per la protezione dei dati personali n. 243 del 15 maggio 2014 |

: {tbl-colwidths="[20,80]" .table-sm .table-striped}

:::


<br>

Si specifica che tali ultime Linee guida sono attualmente in corso di aggiornamento con specifici riferimenti anche al tema del riutilizzo.

Si richiamano altresì:

::: {.no-head}

| label | testo |
| --- | --- |
| [**PAR-06-2013**]{#PAR-06-2013} | [Parere 06/2013 del Gruppo di lavoro Articolo 29 sul riutilizzo dei dati aperti e delle informazioni del settore pubblico](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2013/wp207_it.pdf) |
| [**PAR-05-2014**]{#PAR-05-2014} | [Parere 05/2014 del Gruppo di lavoro Articolo 29 sulle tecniche di anonimizzazione](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_it.pdf) |
| [**PAR-03-2021**]{#PAR-03-2021} | [Parere congiunto del Comitato europeo per la protezione dei dati e del Garante europeo della protezione dei dati 03/2021 sulla proposta di regolamento del Parlamento europeo e del Consiglio relativo alla governance europea dei dati (Atto sulla governance dei dati)](https://edpb.europa.eu/our-work-tools/our-documents/edpbedps-joint-opinion/edpb-edps-joint-opinion-032021-proposal_it) |

: {tbl-colwidths="[20,80]" .table-sm .table-striped}

:::
