---
format:
  html:
    toc: false
---

# Introduzione {.unnumbered}

La costruzione di un mercato unico dei dati e di un'economia basata sugli stessi è l'obiettivo strategico che l'Unione Europea intende perseguire per agevolare la circolazione dei dati a beneficio di tutti, imprese, ricercatori, amministrazioni pubbliche e cittadini. Molteplici sono le iniziative che l'UE sta portando avanti in tale direzione, fra cui la Strategia Europea per i dati[^bookmark5] e la costruzione di spazi di dati comuni e interoperabili, il Regolamento relativo alla governance dei dati (Data Governance Act)[^#_bookmark6], avente ad oggetto la facilitazione della condivisione tra settori e Stati Membri, e la proposta relativa al Data Act[^#_bookmark7], finalizzato a introdurre norme armonizzate per l'accesso equo ai dati e il loro utilizzo.

In questo contesto si pone anche la Direttiva (UE) 2019/1024, cosiddetta Direttiva Open Data, relativa all'apertura dei dati e al riutilizzo dell'informazione del settore pubblico, con cui viene aggiornata e modificata la normativa previgente, definita a livello europeo sin dal 2003 con la prima Direttiva PSI. Le modifiche si sono rese necessarie a seguito della crescita esponenziale della quantità di dati, compresi i dati pubblici, della produzione e raccolta di nuovi tipi di dati, insieme a un'evoluzione costante delle tecnologie per l'analisi, lo sfruttamento e l'elaborazione dei dati, quali l'apprendimento automatico, l'intelligenza artificiale e l'internet delle cose (cfr. Considerando 10 della Direttiva).

In particolare, tali modifiche hanno riguardato i seguenti aspetti: la disponibilità in tempo reale dei dati dinamici mediante mezzi tecnici adeguati; l'aumento dell'offerta di dati pubblici preziosi a fini di riutilizzo, anche provenienti da imprese pubbliche, organizzazioni che svolgono attività di ricerca e organizzazioni che finanziano la ricerca; il contrasto dell'emergere di nuove forme di accordi di esclusiva; il ricorso a deroghe al principio della tariffazione dei costi marginali; la relazione tra la direttiva e alcuni strumenti giuridici correlati, tra cui la Direttiva 2007/2/CE, cosiddetta Direttiva INSPIRE (cfr. Considerando 4 della Direttiva).

Anche in Italia, come indicato anche nel Piano Triennale dell'informatica nella Pubblica Amministrazione[^#_bookmark8], la valorizzazione del patrimonio informativo pubblico è un obiettivo strategico per la Pubblica Amministrazione per affrontare efficacemente le nuove sfide derivanti dalle strategie europee innanzi delineate, garantire la creazione di servizi digitali a valore aggiunto per cittadini, imprese e, in generale, tutti i portatori di interesse e fornire ai policy maker strumenti *data- driven* da utilizzare nei processi decisionali e/o produttivi. Questo obiettivo si può perseguire solo se viene garantito l'accesso a un sempre maggiore numero di dati e vengono migliorate le modalità e la capacità di utilizzarli.

Va in questa direzione il recepimento della Direttiva (UE) 2019/1024, avvenuto con il D. Lgs. 200/2021, che ha modificato, in alcune parti anche sostanzialmente, il D. Lgs. 36/2006 che diventa, quindi, il riferimento normativo nazionale in tema di apertura di dati e riutilizzo del patrimonio informativo pubblico.

L'art. 12 del D. Lgs. 36/2006 dispone che l'Agenzia per l'Italia Digitale adotti "*le Linee guida contenenti le regole tecniche per l'attuazione del presente decreto con le modalità previste dall'articolo 71 del decreto legislativo 7 marzo 2005, n. 82*". Il presente documento rappresenta, pertanto, l'attuazione di detto articolo ed è finalizzato a definire le regole tecniche per l'implementazione delle previsioni normative introdotte dal decreto di cui sopra.

In quanto documento attuativo e considerato il carattere vincolante delle disposizioni in esso contenute anche alla luce del secondo periodo del citato art. 12 (a norma del quale "*In caso di violazione delle disposizioni introdotte dalle Linee guida, il soggetto interessato può rivolgersi al difensore civico per il digitale di cui all'articolo 17, comma 1-quater, del Codice dell'amministrazione digitale e si applicano le sanzioni previste dall'articolo 18-bis, comma 5, dello stesso Codice*"), l'approccio seguito per la redazione è stato quello di definire opportuni requisiti, quindi indicazioni da implementare obbligatoriamente, solo relativamente agli aspetti coperti dal decreto. In particolare, quindi:

- formati e modalità di pubblicazione dei dati di tipo aperto, in generale, e delle specifiche categorie di dati individuate, in particolare;

- richieste di riutilizzo;

- licenze, tariffazione e accordi di esclusiva;

- strumenti di ricerca.

Altri aspetti comunque ritenuti importanti per il processo di apertura dei dati sono stati trattati come raccomandazioni.

[^bookmark5]: <https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A52020DC0066&from=IT>

[^#_bookmark6]: <https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX:32022R0868&from=EN>

[^#_bookmark7]: <https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A52022PC0068&from=IT>

[^#_bookmark8]: <https://www.agid.gov.it/sites/default/files/repository_files/piano_triennale_per_linformatica_nella_pubblica_amministrazione_2021-2023.pdf>
