---
format:
  html:
    toc: false
---

# Prefazione {.unnumbered}

Le presenti Linee Guida rappresentano l'attuazione dell'[art. 12](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2006-01-24;36~art12) del Decreto Legislativo 36/2006, come modificato dal [Decreto Legislativo 200/2021](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2021-11-08;200), recepimento della [Direttiva (UE) 2019/1024](https://eur-lex.europa.eu/legal-content/IT/TXT/?uri=CELEX:32019L1024) (c.d. Direttiva Open Data).

Esse vengono emesse ai sensi dell'[articolo 71](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82~art71) del Decreto Legislativo 82/2005 e s.m.i. recante "Codice dell'Amministrazione Digitale" (di seguito **[CAD](capitolo-2.qmd#CAD)**) e della Determinazione AgID n. 160/2018 recante "*Regolamento per l'adozione di linee guida per l'attuazione del Codice dell'Amministrazione Digitale*"[^#_bookmark2]. Ai sensi del citato art. 71, divengono efficaci il giorno successivo alla loro pubblicazione sul sito istituzionale di AgID e di esse è data notizia sulla Gazzetta Ufficiale della Repubblica italiana.

Le presenti Linee guida sostituiscono, altresì, le *Linee Guida per la valorizzazione del patrimonio informativo pubblico*, adottate con Determinazione Commissariale di AgID n. 95/2014[^#_bookmark3].

[^#_bookmark2]: <https://trasparenza.agid.gov.it/archivio19_regolamenti_0_5376.html>

[^#_bookmark3]: <https://www.agid.gov.it/sites/default/files/repository_files/leggi_decreti_direttive/dt_cs_95_2014dig_linee_guida_open_data_art_52.pdf>
